### ISSUE TITLE
Won't accept load current

### ISSUE THREAD

**Issue by awc105** [CentyLab/AP33772-Cpp#7]
Hi,

I have gone through all the examples and the voltage setting both in fixed PDO and PPS are working fine. However, the first issue I notice is the "fault" led for the AP33772 goes solid on when I select the PDO, and second the output does not tolerate any kind of load and switches off, I have a digital load that has 1ma resolution, and even at like 20mA the AP33772 will switch off the output. 

I have tried this on a samsung 65W charger, apple 87W charger, and apple 29W charger. All with the same results.
The AP33772 dev board I am using is just a generic one made by Mikroe.

Any help or clues would be appreciated

Thanks!

**Comment by centydev** [comment]
Hi @awc105, 

We don't implement the LED in our dev board so its behavior is not something we have much experience. We have has some issue when in rush current can cause some weird behavior. You might have tried this but let's walk through some steps to see if we can I identify the issue.
+ Double check the PDO that you are requesting. LED is said for "Negotiation Mismatch". I dont recall Apple charger has any PPS mode but if you are requesting just fixed PDO then please help me check. I have also released an update for the code should work a bit better if you use `setSupplyVoltageCurrent` function

It might be due to in rush current problem:
+ Try: Request PDO, then attach load
+ Try: Attach load, then request PDO

Let me know.

**Comment by awc105** [comment]
Hey thanks for getting back to me so fast!

As far as the fault led is concerned, after looking at the documentation for the AP33772 (not the S variant, as it's different), the solid "on" stands for a current of less than 500mA, so that appears to be working correctly. Attached is snapshot of the led states from the AP33772 EVM board manual.
![Capture12](https://github.com/user-attachments/assets/d03f750f-b38b-4896-be90-52a1a3edc7e5)

Correct, the only PPS capable charger is the samsung one. I went back and tested the other chargers using fixed pdo with the setsupplyvoltagecurrent you mentioned and  now they are working fine.

However, the odd thing with the samsung charger is that when I switch on the load, it cuts out VBUS entirely, resetting the AP33772...perhaps it's just one to be added to the not compatible list...monitored VBUS in and out of my dev board with a scope and there aren't any odd inrush transients or anything...

I tried requesting then applying load, and applying load and requesting, no difference.

Finally I tried something odd, my load is actually an old HP6632B power supply. It has two quadrant operation so I can sink current with it. Originally I would set the voltage setpoint to 0 and then adjust the load current, in this way it acts as a load. However, if I set the voltage setpoint on the supply to something like 3V and then turn on the load, the charger responds as expected, once current is being drawn, I then go back and set the voltage setpoint to 0 so we are only sinking current and the power from the AP33772 stays on...weird. But it wont work if I don't do this...

**Comment by awc105** [comment]
Just another update, I purchased a different PPS charger, this one: https://www.amazon.com/dp/B0BQLHGLG4?ref=ppx_yo2ov_dt_b_fed_asin_title

It works fine with the load in PPS without any issues. Must be the samsung charger is to blame for my earlier problems.

**Comment by centydev** [comment]
Thank you for your update @awc105. I will add the charger into the supported list.
